CREATE TABLE SKILL_ASSOCIATE 
(
  ID NUMBER(10, 0) NOT NULL 
, NAME VARCHAR2(255 CHAR) NOT NULL 
, EMAIL VARCHAR2(255 CHAR) NOT NULL 
, PASSWORD VARCHAR2(255 CHAR) NOT NULL 
, BATCH_ID NUMBER(10, 0) NOT NULL 
, CONSTRAINT SKILL_USER_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
);

ALTER TABLE SKILL_ASSOCIATE
ADD CONSTRAINT SKILL_USER_UK1 UNIQUE 
(
  EMAIL 
)
ENABLE;
